after_script: [$HOME/travis-ci.sh after-tests]
before_script: [$HOME/travis-ci.sh before-tests]
env: [UPGRADE=none     INSTALL_PANOPOLY_DEMO_FROM_APPS=1, UPGRADE=7.x-1.21]
install: [export UPDATE TRAVIS_BUILD_DIR, cp scripts/travis-ci.sh $HOME/, cd .., $HOME/travis-ci.sh
    system-install]
language: php
matrix:
  allow_failures:
  - {env: UPGRADE=7.x-1.0-rc3}
  fast_finish: true
mysql: {database: drupal, encoding: utf8, username: root}
notifications:
  email:
    on_failure: always
    on_success: always
    recipients: [panopoly-ci@googlegroups.com]
  irc:
    channels: [chat.freenode.net#panopoly]
    on_failure: always
    on_success: always
php: [5.4000000000000004]
script: [$HOME/travis-ci.sh run-tests]
